message/urls.py
from django.conf.urls import url
from . import views

app_name = "message"

urlpatterns = [
    url(r'^SendMsg/(?P<cid>[\w-]+)/$', views.StudentSendMsgView, name="StudentSendMsg")
]

registration/urls.py
from django.conf.urls import url
from . import views

app_name = 'registration'

urlpatterns = [
    url(r'^CreateRegistration/$', views.CreateRegistrationView, name="CreateRegistration"),
    url(r'^UpdateStatus/$', views.UpdateRegStatus, name="StatusUpdate")
]

resultportal/urls.py
"""
Admin site config
"""
from django.contrib import admin

admin.site.site_header = 'Result Board Admin'
admin.site.index_title = 'Result Board Admin'
admin.site.site_title = 'Result Board Admin'

from django.contrib import admin
from django.urls import path, include
from users.views import LandingPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('courses/',include('courses.urls')),
    path('student/', include('student.urls')),
    path('instructor/', include('instructor.urls')),
    path('result/', include('result.urls')),
    path('registration/', include('registration.urls')),
    path('message/', include('message.urls'))
]

student/urls.py
from django.conf.urls import url
from . import views

app_name = "student"

urlpatterns = [
    url(r'^Home/$', views.StudentHomeView, name="Home"),
    url(r'^RegistrationStatus/$', views.RegistrationStatusView , name="RegistrationStatus"),
    url(r'^RegisteredCourses/$', views.RegisteredCoursesView, name="RegisteredCourses"),
    url(r'^ViewResults/$', views.AllResultView, name="ViewResults"),
    url(r'^EditProfile/$', views.EditUserProfileView, name="EditProfile"),
    url(r'^detail/(?P<cid>[\w-]+)/$', views.DetailResultView, name='DetailResultView')
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^CreateProfile/$', views.CreateProfileView, name = "CreateProfile"),
    url(r'^UserProfile/$', views.UserProfileView, name = "UserProfile"),
    url(r'^Home/$', views.HomeView, name="Home"),
    url(r'^FirstLoginPasswordChange/$', views.FirstLoginPasswordChange, name="FirstLoginPasswordChange")
]

result/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from users.models import UserProfileStudent
from courses.models import Course

class Result(models.Model):
    student       = models.ForeignKey(UserProfileStudent, on_delete=models.CASCADE)
    course        = models.ForeignKey(Course, on_delete=models.CASCADE)
    course_name   = models.CharField(max_length=254)
    exam_type     = models.CharField(max_length=254)
    weightage     = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(0), MaxValueValidator(100)])
    student_marks = models.IntegerField()
    total_marks   = models.IntegerField()
    highest_marks = models.IntegerField(null=True, blank=True)
    avg_marks     = models.IntegerField(null=True, blank=True)
    date          = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.course_name
    
    def get_contribution(self):
        return (self.weightage * self.student_marks)/self.total_marks

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render, redirect
from registration.models import Registration
from result.models import Result
from courses.models import Course
from result.utils import get_sub_grade
from message.utils import Inbox
#forms
from users.forms import UserProfileForm
from message.forms import MessageForm

from resultportal.settings import student_login_url

# decortors for protected views
from resultportal.decorators import student_required, userprofile_student_required, first_login_password_changed

# student's home view
@userprofile_student_required   
@student_required(login_url=student_login_url, redirect_field_name='')
@first_login_password_changed
def StudentHomeView(request):

    return render(request, 'student/StudentHome.html')

# view for student's to see their registration status
@userprofile_student_required  
@student_required(login_url=student_login_url, redirect_field_name='')
@first_login_password_changed
def RegistrationStatusView(request):
    
    approved_reg_set = Registration.objects.filter(student_id=request.user.userprofilestudent, is_approved=True)
    pending_reg_set = Registration.objects.filter(student_id=request.user.userprofilestudent, is_approved=False)

    context = {
        'approved_reg': approved_reg_set,
        'pending_reg': pending_reg_set
    }

    return render(request, 'student/RegistrationStatus.html', context)

# view all registered courses
@userprofile_student_required  
@student_required(login_url=student_login_url, redirect_field_name='')
@first_login_password_changed
def RegisteredCoursesView(request):

    reg_set = Registration.objects.filter(student_id=request.user.userprofilestudent, is_approved=True)

    context = {
        'reg_courses': reg_set
    }

    return render(request, 'student/RegisteredCourse.html', context)

#view all recent sent results  
@userprofile_student_required
@student_required(login_url=student_login_url, redirect_field_name='')
@first_login_password_changed
def AllResultView(request):

    results = Result.objects.filter(student=request.user.userprofilestudent).order_by('date').reverse()

    context = {
        'result_set': results
    }

    return render(request, 'student/ViewResults.html', context)

# edit userprofile
@userprofile_student_required  
@student_required(login_url=student_login_url, redirect_field_name='')
@first_login_password_changed
def EditUserProfileView(request):

    try:
        current_profile = request.user.userprofilestudent
    except:
        return redirect('users:CreateProfile')

    if request.method == "POST":
        form = UserProfileForm(request.POST, instance=current_profile)
        if form.is_valid():
            reg_list = Registration.objects.filter(student_id=current_profile)
            # delete existing registrations
            for reg in reg_list:
                reg.delete()
            form.save()
            
            return redirect('student:ViewResults')

    else:
        form = UserProfileForm(instance=current_profile)

    context = {
        'form': form
    }

    return render(request, 'student/EditProfile.html', context)

# detailed view of course and all it's results
@userprofile_student_required  
@student_required(login_url=student_login_url, redirect_field_name='')
@first_login_password_changed
def DetailResultView(request, cid):
    
    student = request.user.userprofilestudent
    course  = Course.objects.get(cid=cid)
    msgform = MessageForm()
    
    results = Result.objects.all().filter(student=student, course=course)

    perc=0
    for res in results:
        perc += res.get_contribution()
    
    grade = get_sub_grade(results=results)

    context = {
        'results': results,
        'course': course,
        'grade': grade,
        'perc': perc,
        'msgform': msgform
    }

    return render(request, 'student/DetailResult.html', context)

#student Inbox
@userprofile_student_required  
@student_required(login_url=student_login_url, redirect_field_name='')
@first_login_password_changed
def StudentInboxView(request):
    messages = Inbox(request.user).get_messages()

    context = {
        'msg': messages
    }

    return render(request, '', context)

student/templates/student/DetailResult.html
{% extends 'temp.html' %}

{% block title %} Detail Result {% endblock %}

{% block side-pan %} 

    <div class="well profile-detail">
        <div class="row">
            <h2>{{ request.user.userprofilestudent.name}}</h2>
            <hr>
            <p><span>Department:</span>  {{ request.user.userprofilestudent.department}}</p>
            <p><span>Roll Number:</span> {{ request.user.userprofilestudent.rollnum}}</p>
            <p><span>Current Semester:</span> {{ request.user.userprofilestudent.semester}}</p>
            <a href="{% url 'account_logout' %}"><button type="button" class="btn btn-danger">Sign out</button></a>
            <a href="{% url 'student:EditProfile' %}"><button type="button" class="btn btn-warning">Edit Profile</button></a>
        </div>
    </div>

{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="detail-result">
                    <h2><span class="label label-primary" style="color:#eeeeee;">{{ course.cid }}  {{ course.name }}</span></h2>
                    <hr>
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Exam</th>
                                <th>Your Marks</th>
                                <th>Total Marks</th>
                                <th>Highest</th>
                                <th>Class Average</th>
                                <th>% of grade</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for res in results %}
                                <tr>
                                    <td>{{ res.exam_type }}</td>
                                    <td>{{ res.student_marks }}</td>
                                    <td>{{ res.total_marks }}</td>
                                    <td>{{ res.highest_marks }}</td>
                                    <td>{{ res.avg_marks }}</td>
                                    <td>{{ res.get_contribution}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Grade</th>
                                <th>Percentage</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ grade }}</td>
                                <td>{{ perc }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="edit-profile">
                    <div class="alert alert-info" role="alert" style="margin: 10px 0 10px 0;">
                        <h5>Send a query to the instructor of this course</h5>
                    </div>
                    <form action="{% url 'message:StudentSendMsg' cid=course.cid %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ msgform}}
                        <input type="submit" value="send" id="conf" class="btn btn-success">
                    </form>
                    {% if messages %}
                        {% for message in messages %}
                            {% if "message-tag" in message.tags %}
                                <div class="alert alert-danger" role="alert" style="margin-top: 10px;">
                                    {{ message}}
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

student/templates/student/EditProfile.html
{% extends 'temp.html' %}

{% block title %} Home {% endblock %}

{% block side-pan %} 

    <div class="well profile-detail">
        <div class="row">
            <h2>{{ request.user.userprofilestudent.name}}</h2>
            <hr>
            <p><span>Department:</span>  {{ request.user.userprofilestudent.department}}</p>
            <p><span>Roll Number:</span> {{ request.user.userprofilestudent.rollnum}}</p>
            <p><span>Current Semester:</span> {{ request.user.userprofilestudent.semester}}</p>
            <a href="{% url 'account_logout' %}"><button type="button" class="btn btn-danger">Sign out</button></a>
        </div>
    </div>

{% endblock %}

{% block body %}

    <div class="conatiner">
        <div class="row">
            <div class="col-sm-12">
                <div class="edit-profile">
                    <span class="label label-warning">Edit Profile</span>
                    <hr>
                    <div class="alert alert-danger" role="alert">
                        Changing your profile will invalid all your current registrations and you will be required
                        to create new registrations for your courses    
                    </div>
                    <form  action="{% url 'student:EditProfile' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form}}
                        <!--Modal Trigger-->
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal" id="modal-trigger">
                            Confirm
                        </button>
                        <input class="btn btn-success" id="conf" type="submit" value="Confirm Changes" style="display: none;"/>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to save changes?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-success" id="confirm-btn">Save changes</button>
        </div>
        </div>
    </div>
    </div>

    <script>
        $(document).ready(function(){
            $("#confirm-btn").click(function(){
                $("#conf").click()
            });
        });
    </script>
{% endblock %}

student/templates/student/RegisteredCourse.html
{% extends 'temp.html' %}

{% block title %} Registered Courses {% endblock %}


{% block side-pan %} 

    <div class="well profile-detail">
        <div class="row">
            <h2>{{ request.user.userprofilestudent.name}}</h2>
            <hr>
            <p><span>Department:</span>  {{ request.user.userprofilestudent.department}}</p>
            <p><span>Roll Number:</span> {{ request.user.userprofilestudent.rollnum}}</p>
            <p><span>Current Semester:</span> {{ request.user.userprofilestudent.semester}}</p>
            <a href="{% url 'account_logout' %}"><button type="button" class="btn btn-danger">Sign out</button></a>
            <a href="{% url 'student:EditProfile' %}"><button type="button" class="btn btn-warning">Edit Profile</button></a>
        </div>
    </div>

{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <h2><span class="label label-primary" style="color:#eeeeee;">Registered Courses</span></h2>
                <hr>
                {% if reg_courses %}

                    {% for course in reg_courses %}
                        <a href="{% url 'student:DetailResultView' cid=course.course_id %}"><button type="button" class="btn btn-info">{{ course.course_id}}</button></a>
                    {% endfor %}

                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

student/templates/student/RegistrationStatus.html
{% extends 'temp.html' %}

{% block title %}
    Registraion Status
{% endblock %}

{% block side-pan %} 

    <div class="well profile-detail">
        <div class="row">
            <h2>{{ request.user.userprofilestudent.name}}</h2>
            <hr>
            <p><span>Department:</span>  {{ request.user.userprofilestudent.department}}</p>
            <p><span>Roll Number:</span> {{ request.user.userprofilestudent.rollnum}}</p>
            <p><span>Current Semester:</span> {{ request.user.userprofilestudent.semester}}</p>
            <a href="{% url 'account_logout' %}"><button type="button" class="btn btn-danger">Sign out</button></a>
            <a href="{% url 'student:EditProfile' %}"><button type="button" class="btn btn-warning">Edit Profile</button></a>
        </div>
    </div>

{% endblock %}

{% block body %}
    <div class="container">
        <div class="registration-status">
            <div class="row">
                <h2><span class="label label-primary" style="color:#eeeeee;">Registration Status</span></h2>
                <a href="{% url 'registration:StatusUpdate' %}"><button type="button" class="btn btn-info">Update Status</button></a>
                {% if approved_reg %}
                    <div class="alert alert-success" role="alert">
                        <h3>Approved</h3>
                    </div>
                    {% for reg in approved_reg %}
                        <div class="well">
                            <p><span>Student name:</span> {{ reg.student_id}}</p>
                            <p><span>course name:</span> {{ reg.course_id}}</p>
                            <p><span>Registration status:</span> approved</p>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="row">
                {% if pending_reg %}
                    <div class="alert alert-danger" role="alert">
                        <h3>Pending</h3>
                    </div>
                    {% for reg in pending_reg %}
                        <div class="well">
                            <p><span>Student name:</span> {{ reg.student_id}}</p>
                            <p><span>course name:</span> {{ reg.course_id}}</p>
                            <p><span>Registration status:</span> pending</p>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}


        
            
            

student/templates/student/StudentHome.html
{% extends 'temp.html' %}

{% block title %} Home {% endblock %}

{% block side-pan %} 

    <div class="well profile-detail">
        <div class="row">
            <h2>{{ request.user.userprofilestudent.name}}</h2>
            <hr>
            <p><span>Department:</span>  {{ request.user.userprofilestudent.department}}</p>
            <p><span>Roll Number:</span> {{ request.user.userprofilestudent.rollnum}}</p>
            <p><span>Current Semester:</span> {{ request.user.userprofilestudent.semester}}</p>
            <a href="{% url 'account_logout' %}"><button type="button" class="btn btn-danger">Sign out</button></a>
            <a href="{% url 'student:EditProfile' %}"><button type="button" class="btn btn-warning">Edit Profile</button></a>
        </div>
    </div>

{% endblock %}

{% block body %} 

    <div class="container">
        <div class="row">
            <a href="{% url 'registration:CreateRegistration' %}">Course Registration</a>
            <br>
            <a href="{% url 'student:RegistrationStatus' %}">View Registrations</a>
            <br>
            <a href="{% url 'student:RegisteredCourses' %}">Registered Courses</a>
            <br>
            <a href="{% url 'student:ViewResults' %}">View Results</a>
        </div>
    </div>

{% endblock %}

student/templates/student/ViewResults.html
{% extends 'temp.html' %}

{% block title %} Results {% endblock %}

{% block side-pan %} 

    <div class="well profile-detail">
        <div class="row">
            <h2>{{ request.user.userprofilestudent.name}}</h2>
            <hr>
            <p><span>Department:</span>  {{ request.user.userprofilestudent.department}}</p>
            <p><span>Roll Number:</span> {{ request.user.userprofilestudent.rollnum}}</p>
            <p><span>Current Semester:</span> {{ request.user.userprofilestudent.semester}}</p>
            <a href="{% url 'account_logout' %}"><button type="button" class="btn btn-danger">Sign out</button></a>
            <a href="{% url 'student:EditProfile' %}"><button type="button" class="btn btn-warning">Edit Profile</button></a>
        </div>
    </div>

{% endblock %}


{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2><span class="label label-primary">Results</span></h2>
                <hr>
                <div class="result-card">
                    {% if result_set %}
                    {% for result in result_set %}
                        <a href="{% url 'student:DetailResultView' cid=result.course.cid %}" style="text-decoration: none; color: black;"> 
                            <div class="well">
                                <h3>{{ result.course}} {{ result.course_name}}</h3>
                                <hr>
                                <span>Exam Type: </span>{{ result.exam_type}} <br>
                                <span>Your Marks: </span> {{ result.student_marks}} <br>
                                <span>Total Marks: </span> {{ result.total_marks}} <br>
                                <span>Highest Marks: </span> {{ result.highest_marks}} <br>
                                <span>Avg Marks: </span> {{ result.avg_marks}}
                            </div>
                        </a>
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}