result/urls.py
from django.conf.urls import url
from . import views

app_name = 'result'

urlpatterns = [
    url(r'^CreateResult/$', views.CreateResult, name="CreateResult"),
    url(r'^GetCourseName/$', views.GetCourseName, name="GetCourseName")
]

resultportal/urls.py
"""
Admin site config
"""
from django.contrib import admin

admin.site.site_header = 'Result Board Admin'
admin.site.index_title = 'Result Board Admin'
admin.site.site_title = 'Result Board Admin'

from django.contrib import admin
from django.urls import path, include
from users.views import LandingPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('courses/',include('courses.urls')),
    path('student/', include('student.urls')),
    path('instructor/', include('instructor.urls')),
    path('result/', include('result.urls')),
    path('registration/', include('registration.urls')),
    path('message/', include('message.urls'))
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^CreateProfile/$', views.CreateProfileView, name = "CreateProfile"),
    url(r'^UserProfile/$', views.UserProfileView, name = "UserProfile"),
    url(r'^Home/$', views.HomeView, name="Home"),
    url(r'^FirstLoginPasswordChange/$', views.FirstLoginPasswordChange, name="FirstLoginPasswordChange")
]

result/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from users.models import UserProfileStudent
from courses.models import Course

class Result(models.Model):
    student       = models.ForeignKey(UserProfileStudent, on_delete=models.CASCADE)
    course        = models.ForeignKey(Course, on_delete=models.CASCADE)
    course_name   = models.CharField(max_length=254)
    exam_type     = models.CharField(max_length=254)
    weightage     = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(0), MaxValueValidator(100)])
    student_marks = models.IntegerField()
    total_marks   = models.IntegerField()
    highest_marks = models.IntegerField(null=True, blank=True)
    avg_marks     = models.IntegerField(null=True, blank=True)
    date          = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.course_name
    
    def get_contribution(self):
        return (self.weightage * self.student_marks)/self.total_marks

result/forms.py
from django import forms
from courses.models import Course

class ResultForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ResultForm, self).__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.filter(instructor=self.request.user.userprofilefaculty)

    course = forms.ModelChoiceField(queryset=None)
    course_name = forms.CharField(max_length=254)
    exam_type = forms.CharField(max_length=254)
    total_marks = forms.IntegerField()
    weightage = forms.DecimalField(max_digits=5, decimal_places=2, max_value=100, min_value=0)
    highest_marks = forms.IntegerField()
    avg_marks = forms.IntegerField()
    

    

result/views.py
from django.shortcuts import render
from . forms import ResultForm
from . models import Result
from users.models import UserProfileStudent
from courses.models import Course
from resultportal.decorators import instructor_required
from django.http import JsonResponse
from django.contrib import messages
from registration.models import Registration
from instructor.models import ResultHistory

# openpyxl module
import openpyxl

# create a result 
# access restricted to faculty
@instructor_required(login_url='account_login')
def CreateResult(request):
    if request.method == "POST":
        excel_file = request.FILES["excel_file"]
        form = ResultForm(request.POST, request=request)

        if form.is_valid():
            wb = openpyxl.load_workbook(excel_file)
            worksheet = wb["Sheet1"]

            form_input = form.cleaned_data

            for row in worksheet.iter_rows():
                row_data = list()
                for cell in row:
                    row_data.append(str(cell.value))

                try:
                    user_inst = UserProfileStudent.objects.get(rollnum=row_data[0])
                except:
                    user_inst = None
                course_inst = Course.objects.get(cid=form_input.get('course'))
    
                if user_inst != None:
                    try:
                        user_reg = Registration.objects.get(student_id=user_inst, course_id=course_inst)
                    except:
                        user_reg = None
                    if user_reg != None and user_reg.is_approved == True:
                        Result.objects.create(
                            student = user_inst,
                            course  = course_inst,
                            course_name = course_inst.name,
                            exam_type = form_input.get('exam_type'),
                            student_marks = row_data[1],
                            total_marks = form_input.get('total_marks'),
                            highest_marks = form_input.get('highest_marks'),
                            avg_marks = form_input.get('avg_marks'),
                            weightage = form_input.get('weightage')
                        )
            messages.info(request, "Results sent Successfully", extra_tags="result-success")
            ResultHistory.objects.create(instructor=request.user.userprofilefaculty, excel_file=excel_file, exam_type=form_input.get('exam_type'))

    else:
        form = ResultForm(request=request)

    context = {
        'form': form
    }

    return render(request, 'result/CreateResult.html', context)

#get course name from course id via ajax request
def GetCourseName(request):
    cid = request.GET.get('cid', None)
    course = Course.objects.get(pk=cid)
    cname =  course.name
    
    data = {'course_name': cname}
    return JsonResponse(data)

result/templates/result/CreateResult.html
{% extends 'instructor/Home.html' %}

{% block title %} Create Result {% endblock %}

{% block body %}
<!--Script to get course name on the basis of selected course--> 
<script>
    $(document).ready(function(){
        $("#id_course").change(
        function get_course_name()
        {
            var cid = $("#id_course").val();
            $.ajax({
                url: '{% url "result:GetCourseName" %}',
                data: {'cid': cid},
                dataType: 'json',
                success: function(data){console.log(data.course_name); var cid = $("#id_course_name").val(data.course_name);},
                error : function(data){console.log("error")}
            });
        }
    );
    });
</script>

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="edit-profile">
                    <h2><span class="label label-warning">Send Results</span></h2>
                    <hr>
                    <form action="{% url 'result:CreateResult' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        {{ form }}
                        <h5>Upload a excel file</h5>
                        <input type="file" title="Upload Excel file" name="excel_file" required="required" id="file-input">
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal" id="modal-trigger">
                            Confirm
                        </button>
                        <input type="submit" class="btn btn-success" value="Send" id="send" style="display:none">
                    </form>

                {% if messages %}
                    {% for message in messages %}
                        {% if "result-success" in message.tags %}
                            <div class="alert alert-success" role="alert">
                                {{ message}}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Are you sure you want Send results?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
    
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="confirm-btn">send</button>
            </div>
            </div>
        </div>
        </div>
    
        <script>
            $(document).ready(function(){
                $("#confirm-btn").click(function(){
                    $("#send").click()
                });
            });
        </script>
{% endblock %}