registration/urls.py
from django.conf.urls import url
from . import views

app_name = 'registration'

urlpatterns = [
    url(r'^CreateRegistration/$', views.CreateRegistrationView, name="CreateRegistration"),
    url(r'^UpdateStatus/$', views.UpdateRegStatus, name="StatusUpdate")
]

resultportal/urls.py
"""
Admin site config
"""
from django.contrib import admin

admin.site.site_header = 'Result Board Admin'
admin.site.index_title = 'Result Board Admin'
admin.site.site_title = 'Result Board Admin'

from django.contrib import admin
from django.urls import path, include
from users.views import LandingPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('courses/',include('courses.urls')),
    path('student/', include('student.urls')),
    path('instructor/', include('instructor.urls')),
    path('result/', include('result.urls')),
    path('registration/', include('registration.urls')),
    path('message/', include('message.urls'))
]

student/urls.py
from django.conf.urls import url
from . import views

app_name = "student"

urlpatterns = [
    url(r'^Home/$', views.StudentHomeView, name="Home"),
    url(r'^RegistrationStatus/$', views.RegistrationStatusView , name="RegistrationStatus"),
    url(r'^RegisteredCourses/$', views.RegisteredCoursesView, name="RegisteredCourses"),
    url(r'^ViewResults/$', views.AllResultView, name="ViewResults"),
    url(r'^EditProfile/$', views.EditUserProfileView, name="EditProfile"),
    url(r'^detail/(?P<cid>[\w-]+)/$', views.DetailResultView, name='DetailResultView')
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^CreateProfile/$', views.CreateProfileView, name = "CreateProfile"),
    url(r'^UserProfile/$', views.UserProfileView, name = "UserProfile"),
    url(r'^Home/$', views.HomeView, name="Home"),
    url(r'^FirstLoginPasswordChange/$', views.FirstLoginPasswordChange, name="FirstLoginPasswordChange")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
      <div class="container">
        <div class="row">
          <div class="col-sm-4 side-pan">
              <h1 class="banner">Result Board</h1>
          </div>
          <div class="col-sm-8">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
      {% endblock %}
      {% block extra_body %}
    {% endblock %}
  </body>
</html>

templates/temp.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    
    <title>{% block title %} Title Block {% endblock %}</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-4 side-pan">
                {% block side-pan %}
                
                {% endblock %}

                {% block nav %}
                    <ul class="nav flex-column">
                        <li class="nav-item">
                        <a class="nav-link " href="{% url 'student:ViewResults' %}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="{% url 'registration:CreateRegistration' %}">Create Registration</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'student:RegistrationStatus' %}">View Registrations</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'student:RegisteredCourses' %}">View Registered courses</a>
                        </li>
                    </ul>
                {% endblock %}
            </div>
            <div class="col-sm-8">
                {% block body %} 
                    <p>Body Block</p> 
                {% endblock %}
            </div>
        </div>
    </div>
</div>    
</body>
</html>


            

        
        

        