instructor/urls.py
from django.conf.urls import url
from . import views

app_name="instructor"

urlpatterns = [
    url(r'^Home/$', views.HomeView, name="HomeView"),
    url(r'^ResultHistory/$', views.SentResultView, name="SentResultView"),
    url(r'^get_result_preview/$', views.ResultPreview, name="ResultPreview"),
    url(r'^Inbox/$', views.InstructorInboxView, name="Inbox")
]

result/urls.py
from django.conf.urls import url
from . import views

app_name = 'result'

urlpatterns = [
    url(r'^CreateResult/$', views.CreateResult, name="CreateResult"),
    url(r'^GetCourseName/$', views.GetCourseName, name="GetCourseName")
]

resultportal/urls.py
"""
Admin site config
"""
from django.contrib import admin

admin.site.site_header = 'Result Board Admin'
admin.site.index_title = 'Result Board Admin'
admin.site.site_title = 'Result Board Admin'

from django.contrib import admin
from django.urls import path, include
from users.views import LandingPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('courses/',include('courses.urls')),
    path('student/', include('student.urls')),
    path('instructor/', include('instructor.urls')),
    path('result/', include('result.urls')),
    path('registration/', include('registration.urls')),
    path('message/', include('message.urls'))
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^CreateProfile/$', views.CreateProfileView, name = "CreateProfile"),
    url(r'^UserProfile/$', views.UserProfileView, name = "UserProfile"),
    url(r'^Home/$', views.HomeView, name="Home"),
    url(r'^FirstLoginPasswordChange/$', views.FirstLoginPasswordChange, name="FirstLoginPasswordChange")
]

instructor/models.py
from django.db import models
from users.models import UserProfileFaculty

class ResultHistory(models.Model):
    instructor = models.ForeignKey(UserProfileFaculty, on_delete=models.CASCADE)
    excel_file = models.FileField(upload_to='docs/')
    created_on = models.DateTimeField(auto_now_add=True)
    exam_type = models.CharField(max_length=254)

    def __str__(self):
        return self.instructor.name

    def get_date(self):
        return self.created_on.strftime('%d/%m/%Y')

instructor/forms.py
from django import forms

instructor/views.py
from django.shortcuts import render
from . models import ResultHistory
from users.models import UserProfileFaculty
from django.http import JsonResponse
from message.utils import Inbox
import json
import openpyxl

# decorators
from resultportal.decorators import instructor_required

# Home view
@instructor_required(login_url='account_login')
def HomeView(request):
    return render(request, 'instructor/Home.html')

@instructor_required
def SentResultView(request):
    ins = request.user.userprofilefaculty
    prev_results = ResultHistory.objects.filter(instructor=ins)
    
    context = {
        'prev_results':prev_results
    }
    return render(request, 'instructor/ResultHistory.html', context)

# Result Preview
class PreviewModel():
    def __init__(self, rollnum, marks):
        self.rollnum = rollnum
        self.marks = marks

#ajax request for result preview
def ResultPreview(request):
    id = request.GET.get('id', None)
    ins = ResultHistory.objects.get(pk=id)
    excel_file = ins.excel_file

    desc = {
        'exam_type': ins.exam_type,
        'created_on': ins.get_date()
    }

    wb = openpyxl.load_workbook(excel_file)
    worksheet = wb["Sheet1"]

    obj_list = list()

    for row in worksheet.iter_rows():
        row_data = list()
        for cell in row:
            row_data.append(str(cell.value))
        obj = PreviewModel(row_data[0], row_data[1])
        obj_list.append(obj)

    json_obj = json.dumps([ob.__dict__ for ob in obj_list])
    data = {
        'desc': desc,
        'json': json_obj
    }
    return JsonResponse(data, safe=False)

# inbox
def InstructorInboxView(request):
    messages = Inbox(request.user).get_messages()

    context = {
        'msg': messages
    }

    return render(request, 'instructor/Inbox.html', context)

    

instructor/templates/instructor/Home.html
{% extends 'temp.html' %}

{% block title %} Home {% endblock %}

{% block nav %} 
    <ul class="nav flex-column">
        <li class="nav-item">
        <a class="nav-link " href="{% url 'instructor:HomeView' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'result:CreateResult' %}">Send Results</a>
        </li>
        <li class="nav-item">
        <a class="nav-link " href="{% url 'instructor:SentResultView' %}">Result History</a>
        </li>
    </ul>
{% endblock %}

{% block side-pan %} 
    <div class="well profile-detail">
        <div class="row">
            <h2>{{ request.user.userprofilefaculty.name}}</h2>
            <hr>
            <p>
                <span>Department:</span>  {{ request.user.userprofilefaculty.department}}
                <a href="{% url 'instructor:Inbox' %}">
                    <span class="glyphicon glyphicon-envelope" style="float:right; font-size: 200%; margin: 0 5px 0 5px;"></span>
                </a>
            </p>

            <a href="{% url 'account_logout' %}"><button type="button" class="btn btn-danger">Sign out</button></a>
        </div>
    </div>
{% endblock %}

{% block body %} 
{% endblock%}

instructor/templates/instructor/Inbox.html
{% extends 'instructor/Home.html' %}

{% block title %} Inbox {% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="inbox">
                    <h2><span class="label label-warning">Inbox</span></h2>
                    {% for m in msg %}
                        <div class="well">
                            <h4 style="font-weight: bold;">
                                {{ m.subject}}
                                <a href="">
                                    <span   
                                        class="glyphicon glyphicon-trash" 
                                        style="float:right; margin: 0 5px 0 5px; "
                                        data-toggle="tootip" title="Delete Message">    
                                    </span>
                                </a> 
                                <a href="">
                                    <span 
                                        class="glyphicon glyphicon-send" 
                                        style="float:right; margin: 0 5px 0 5px;"
                                        data-toggle="tootip" title="Reply">
                                    </span>
                                </a>
                            </h4>
                            <span style="font-weight: bold  ;">From: {{ m.sender}} Name: {{ m.sender.userprofilestudent.name}}</span><br>
                            <p>{{ m.body}}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
{% endblock %}

instructor/templates/instructor/ResultHistory.html
{% extends 'instructor/Home.html' %}

{% block title %} Result History {% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="res-hist">
                    <h2><span class="label label-warning">Result History</span></h2>
                    <ul class="list-group list-group-flush">
                        {% for res in prev_results %}
                            <li class="list-group-item" onclick="get_result_preview({{ res.pk}})">{{ res.exam_type}} - {{ res.get_date}}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong" id="mod-trig" style="display: none">
        Launch demo modal
    </button>
    
    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Roll Number</th>
                            <th scope="col">Marks</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">

                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>

    <script>
        function get_result_preview(id){
            $.ajax({
                url: '{% url "instructor:ResultPreview" %}',
                data: {'id': id},
                dataType: 'json',
                success:  function(data){
                    var content;
                    var desc = data.desc;
                    var json = data.json;
                    json = JSON.parse(json);
                    for(var i=0; i< json.length; i+=1){
                        var obj = json[i];
                        content += `<tr> <td>${obj.rollnum}</td> <td>${obj.marks}</td> </tr>`
                    }

                    $("#tbody").html(content);
                    $("#exampleModalLongTitle").html(`Exam Type: ${desc.exam_type} <br> Created on: ${desc.created_on}`);
                    $("#mod-trig").click();
                },
                error: function(data){console.log("error");}
            });
        }
    </script>
{% endblock%}